admin_addr: 127.0.0.1:9090
basic_auth:
  username: admin
  password: password
forwards:
  - protocols:
      - tcp
      - udp
    from: 0.0.0.0:15353
    to: 114.114.114.114:53
    allowed_ips:
      - 192.168.1.0/24
  - protocols:
      - tcp
    from: 0.0.0.0:18080
    to: 127.0.0.1:8080
    allowed_ips:
      - 192.168.1.0/24
